events {}

http {
  upstream witch_client {
    server client:4173;
  }

  upstream witch_server {
    server server:5001;
  }

  server {
    listen 80;
    server_name _;

    location /api/ {
      proxy_pass http://witch_server;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /socket.io/ {
      proxy_pass http://witch_server;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }

    location / {
      proxy_pass http://witch_client;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
    }
  }
}
